# Generated by Django 6.1 on 2026-09-02 04:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej. PRJ-2026-001', max_length=50, unique=True, verbose_name='Código del Proyecto')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción / Alcance')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalización Estimada')),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='Duración (Meses)')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Presupuesto Estimado')),
                ('status', models.CharField(choices=[('PLANNING', 'En Planificación'), ('IN_PROGRESS', 'En Ejecución'), ('STAND_BY', 'En Espera (Stand-by)'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PLANNING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('role', models.CharField(help_text='Ej. Modelador Revit, Renderista, Desarrollador', max_length=100, verbose_name='Rol / Especialidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo en la empresa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros del Equipo',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('color_code', models.CharField(default='#3B82F6', max_length=20, verbose_name='Código de Color (HEX)')),
            ],
            options={
                'verbose_name': 'Estado del Equipo',
                'verbose_name_plural': 'Estados de Equipos',
            },
        ),
        migrations.CreateModel(
            name='TechnicalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Área Técnica',
                'verbose_name_plural': 'Áreas Técnicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Hito')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('target_date', models.DateField(verbose_name='Fecha Objetivo')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Cumplimiento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Cumplido'), ('DELAYED', 'Atrasado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='DriveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Enlace')),
                ('drive_url', models.URLField(max_length=500, verbose_name='URL de Google Drive')),
                ('file_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Google Drive File/Folder ID')),
                ('file_type', models.CharField(choices=[('FOLDER', 'Carpeta Principal de Proyecto'), ('DOCUMENT', 'Documento / Especificación Técnica'), ('BIM_MODEL', 'Modelo BIM / Revit'), ('RENDER_360', 'Render / Recorrido Virtual 360°'), ('SPREADSHEET', 'Hoja de Cálculo / Presupuesto'), ('OTHER', 'Otro')], default='FOLDER', max_length=20, verbose_name='Tipo de Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_links', to='core.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Enlace de Drive',
                'verbose_name_plural': 'Enlaces de Drive',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Tarea')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Duración (Días)')),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso (%)')),
                ('is_critical_path', models.BooleanField(default=False, help_text='Calculado por el motor de optimización', verbose_name='¿Es Ruta Crítica?')),
                ('tolerance_days', models.PositiveIntegerField(default=7, help_text='Margen de seguridad por defecto: 7 días', verbose_name='Tolerancia / Holgura (Días)')),
                ('status', models.CharField(choices=[('TODO', 'Por Hacer'), ('IN_PROGRESS', 'En Curso'), ('REVIEW', 'En Revisión'), ('DONE', 'Finalizada')], default='TODO', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.milestone', verbose_name='Hito Asociado')),
                ('predecessors', models.ManyToManyField(blank=True, related_name='successors', to='core.task', verbose_name='Tareas Predecesoras')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project', verbose_name='Proyecto')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.teammember', verbose_name='Responsable Asignado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.technicalarea', verbose_name='Área Técnica')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(help_text='Ej. M2 de encofrado, M3 de concreto, Renders', max_length=50, verbose_name='Unidad de Medida')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad Total')),
                ('rate_per_day', models.DecimalField(decimal_places=2, help_text='Ej. M2 por día', max_digits=10, verbose_name='Rendimiento Diario Estimado')),
                ('divisor', models.PositiveIntegerField(default=5, help_text='Factor de aceleración para cálculo de reducción', verbose_name='Factor Divisor / Reductor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='core.project', verbose_name='Proyecto')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='core.task', verbose_name='Tarea Específica')),
            ],
            options={
                'verbose_name': 'Métrica de Rendimiento',
                'verbose_name_plural': 'Métricas de Rendimiento',
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.teamstatus', verbose_name='Estado Actual'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='technical_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.technicalarea', verbose_name='Área Técnica'),
        ),
    ]
