# Generated by Django 6.1 on 2026-09-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivelink',
            name='project',
        ),
        migrations.AddField(
            model_name='drivelink',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drive_links', to='core.task', verbose_name='Tarea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivelink',
            name='file_type',
            field=models.CharField(choices=[('FOLDER', 'Carpeta de Tarea / Entregable'), ('DOCUMENT', 'Documento / Especificación Técnica'), ('BIM_MODEL', 'Modelo BIM / Revit'), ('RENDER_360', 'Render / Recorrido Virtual 360°'), ('SPREADSHEET', 'Hoja de Cálculo / Presupuesto'), ('OTHER', 'Otro')], default='DOCUMENT', max_length=20, verbose_name='Tipo de Archivo'),
        ),
    ]
