# Generated by Django 6.1 on 2026-09-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_drivelink_project_drivelink_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='core.project', verbose_name='Proyecto Asignado'),
        ),
    ]
