# Generated by Django 6.1 on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Rol / Cargo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción / Funciones del Puesto')),
                ('can_manage_projects', models.BooleanField(default=False, verbose_name='¿Puede gestionar proyectos?')),
                ('can_manage_tasks', models.BooleanField(default=True, verbose_name='¿Puede gestionar tareas?')),
                ('can_view_metrics', models.BooleanField(default=True, verbose_name='¿Puede ver métricas?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technical_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.technicalarea', verbose_name='Área Técnica')),
            ],
            options={
                'verbose_name': 'Rol / Cargo Técnico',
                'verbose_name_plural': 'Roles / Cargos Técnicos',
                'ordering': ['technical_area', 'name'],
                'unique_together': {('technical_area', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.role', verbose_name='Rol / Cargo Asignado'),
        ),
    ]
