# Generated by Django 6.1 on 2026-09-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'En Planificación'), ('IN_PROGRESS', 'En Ejecución'), ('STAND_BY', 'En Espera (Stand-by)'), ('COMPLETED', 'Completado'), ('RISK', 'En Riesgo'), ('CANCELLED', 'Cancelado')], default='PLANNING', max_length=20, verbose_name='Estado'),
        ),
    ]
