# Generated by Django on 2026-09-25
from django.db import migrations


def clear_demo_projects(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    TeamMember = apps.get_model('core', 'TeamMember')
    Milestone = apps.get_model('core', 'Milestone')
    Task = apps.get_model('core', 'Task')
    DriveLink = apps.get_model('core', 'DriveLink')
    PerformanceMetric = apps.get_model('core', 'PerformanceMetric')

    # Desvincular integrantes de proyectos
    TeamMember.objects.all().update(project=None)

    # Eliminar tareas, hitos, métricas y enlaces asociados
    DriveLink.objects.all().delete()
    PerformanceMetric.objects.all().delete()
    Task.objects.all().delete()
    Milestone.objects.all().delete()

    # Eliminar proyectos
    Project.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_status'),
    ]

    operations = [
        migrations.RunPython(clear_demo_projects, migrations.RunPython.noop),
    ]
