# Generated by Django 6.1 on 2026-09-29 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clear_demo_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemetric',
            options={'verbose_name': 'MÃ©trica de Rendimiento', 'verbose_name_plural': 'MÃ©tricas de Rendimiento'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['technical_area', 'name'], 'verbose_name': 'Rol / Cargo TÃ©cnico', 'verbose_name_plural': 'Roles / Cargos TÃ©cnicos'},
        ),
        migrations.AlterModelOptions(
            name='technicalarea',
            options={'ordering': ['name'], 'verbose_name': 'Ã\x81rea TÃ©cnica', 'verbose_name_plural': 'Ã\x81reas TÃ©cnicas'},
        ),
        migrations.AlterField(
            model_name='drivelink',
            name='file_type',
            field=models.CharField(choices=[('FOLDER', 'Carpeta de Tarea / Entregable'), ('DOCUMENT', 'Documento / EspecificaciÃ³n TÃ©cnica'), ('BIM_MODEL', 'Modelo BIM / Revit'), ('RENDER_360', 'Render / Recorrido Virtual 360Â°'), ('SPREADSHEET', 'Hoja de CÃ¡lculo / Presupuesto'), ('OTHER', 'Otro')], default='DOCUMENT', max_length=20, verbose_name='Tipo de Archivo'),
        ),
        migrations.AlterField(
            model_name='drivelink',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo del Enlace'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='divisor',
            field=models.PositiveIntegerField(default=5, help_text='Factor de aceleraciÃ³n para cÃ¡lculo de reducciÃ³n', verbose_name='Factor Divisor / Reductor'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='rate_per_day',
            field=models.DecimalField(decimal_places=2, help_text='Ej. M2 por dÃ\xada', max_digits=10, verbose_name='Rendimiento Diario Estimado'),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='core.task', verbose_name='Tarea EspecÃ\xadfica'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(help_text='Ej. PRJ-2026-001', max_length=50, unique=True, verbose_name='CÃ³digo del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n / Alcance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration_months',
            field=models.PositiveIntegerField(default=1, verbose_name='DuraciÃ³n (Meses)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de FinalizaciÃ³n Estimada'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'En PlanificaciÃ³n'), ('IN_PROGRESS', 'En EjecuciÃ³n'), ('STAND_BY', 'En Espera (Stand-by)'), ('COMPLETED', 'Completado'), ('RISK', 'En Riesgo'), ('CANCELLED', 'Cancelado')], default='PLANNING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_projects',
            field=models.BooleanField(default=False, verbose_name='Â¿Puede gestionar proyectos?'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_tasks',
            field=models.BooleanField(default=True, verbose_name='Â¿Puede gestionar tareas?'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_view_metrics',
            field=models.BooleanField(default=True, verbose_name='Â¿Puede ver mÃ©tricas?'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n / Funciones del Puesto'),
        ),
        migrations.AlterField(
            model_name='role',
            name='technical_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.technicalarea', verbose_name='Ã\x81rea TÃ©cnica'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.technicalarea', verbose_name='Ã\x81rea TÃ©cnica'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n Detallada'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, verbose_name='DuraciÃ³n (DÃ\xadas)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_critical_path',
            field=models.BooleanField(default=False, help_text='Calculado por el motor de optimizaciÃ³n', verbose_name='Â¿Es Ruta CrÃ\xadtica?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Por Hacer'), ('IN_PROGRESS', 'En Curso'), ('REVIEW', 'En RevisiÃ³n'), ('DONE', 'Finalizada')], default='TODO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo de la Tarea'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tolerance_days',
            field=models.PositiveIntegerField(default=7, help_text='Margen de seguridad por defecto: 7 dÃ\xadas', verbose_name='Tolerancia / Holgura (DÃ\xadas)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo ElectrÃ³nico'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Â¿EstÃ¡ activo en la empresa?'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='technical_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.technicalarea', verbose_name='Ã\x81rea TÃ©cnica'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='color_code',
            field=models.CharField(default='#3B82F6', max_length=20, verbose_name='CÃ³digo de Color (HEX)'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='technicalarea',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='technicalarea',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ã\x81rea'),
        ),
        migrations.CreateModel(
            name='BIMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Modelo')),
                ('urn', models.CharField(max_length=500, verbose_name='URN de Autodesk')),
                ('object_id', models.CharField(max_length=500, verbose_name='Object ID (OSS)')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bim_models', to='core.project')),
            ],
            options={
                'verbose_name': 'Modelo BIM',
                'verbose_name_plural': 'Modelos BIM',
                'ordering': ['-created_at'],
            },
        ),
    ]
