# Generated by Django 6.1 on 2026-09-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bimmodel_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimmodel',
            name='uploaded_by',
        ),
    ]
